version: 2.1
jobs:
  build:
    # parameters:
    #   name: 
    #     type: string
    #     default: 
    working_directory: ~/project
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - run: ls -la
      - run:
          name: Update NPM
          command: "npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run: npm install --save-dev firebase-tools    
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build application for production
          command: npm run build
      - run:
          name: Deploy app to Firebase
          command: |
            if [ $CIRCLE_BRANCH = "main" ]; then \
              ./node_modules/.bin/firebase use default
              ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
            else \
              echo "not deploying on $CIRCLE_BRANCH"; \
            fi

workflows:
  build-and-deploy:
    jobs:
      - build